package Menu_System;

import Maincarrace.MainF;
import Objects.Player;
import gameloop.GameLoop;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

public class CarSelect extends JFrame {

    /**
     * Creates new form CarSelect
     */
    public CarSelect() {
        setUndecorated(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        car2 = new javax.swing.JButton();
        car1 = new javax.swing.JButton();
        car4 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        car3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        car2.setBackground(new java.awt.Color(255, 255, 204));
        car2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maincarrace/images/2.png"))); // NOI18N
        car2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car2ActionPerformed(evt);
            }
        });
        jPanel1.add(car2);
        car2.setBounds(960, 70, 185, 150);

        car1.setBackground(new java.awt.Color(255, 255, 204));
        car1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maincarrace/images/1.png"))); // NOI18N
        car1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car1ActionPerformed(evt);
            }
        });
        jPanel1.add(car1);
        car1.setBounds(190, 70, 185, 150);

        car4.setBackground(new java.awt.Color(255, 255, 204));
        car4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maincarrace/images/4.png"))); // NOI18N
        car4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car4ActionPerformed(evt);
            }
        });
        jPanel1.add(car4);
        car4.setBounds(960, 490, 185, 150);

        back.setBackground(new java.awt.Color(-16776961,true));
        back.setFont(new java.awt.Font("Monospaced", 1, 18));
        back.setForeground(new java.awt.Color(-16711681,true));
        back.setText("BACK");
        back.setToolTipText("");
        back.setContentAreaFilled(false);
        back.setPreferredSize(new java.awt.Dimension(153, 33));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backmousePressed(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(600, 320, 160, 23);

        car3.setBackground(new java.awt.Color(255, 255, 204));
        car3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maincarrace/images/3.png"))); // NOI18N
        car3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car3ActionPerformed(evt);
            }
        });
        jPanel1.add(car3);
        car3.setBounds(190, 490, 185, 150);

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Green Racer");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1010, 250, 100, 20);

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("SELECT YOUR CAR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(560, 70, 270, 50);

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Blue Racer");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 450, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Yellow Racer");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1010, 450, 100, 20);

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Red Racer");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 250, 80, 20);

        next.setBackground(new java.awt.Color(-16776961,true));
        next.setFont(new java.awt.Font("Monospaced", 1, 18));
        next.setForeground(new java.awt.Color(-16711681,true));
        next.setText("NEXT");
        next.setToolTipText("");
        next.setContentAreaFilled(false);
        next.setPreferredSize(new java.awt.Dimension(153, 33));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextmousePressed(evt);
            }
        });
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(600, 370, 160, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backmousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backmousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_backmousePressed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        close();
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_backActionPerformed
//car selection calling from the player class
    private void car1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car1ActionPerformed
        Player.changeCar(1);
    }//GEN-LAST:event_car1ActionPerformed

    private void car2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car2ActionPerformed
        Player.changeCar(2);
    }//GEN-LAST:event_car2ActionPerformed

    private void car3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car3ActionPerformed
        Player.changeCar(3);
    }//GEN-LAST:event_car3ActionPerformed

    private void car4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car4ActionPerformed
        Player.changeCar(4);
    }//GEN-LAST:event_car4ActionPerformed

    private void nextmousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextmousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextmousePressed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        close(); //close the car selection frame
        GameLoop.type = "1p"; //sets mode in Game Loop to 1 player
//        MapSelect ms = new MapSelect();
//        ms.setVisible(true);
        MainF m = new MainF(); //calls the game from MainF
        
    }//GEN-LAST:event_nextActionPerformed

   
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarSelect().setVisible(true);
            }
        });
    }
    //close the carselector jframe
    private void close() {
        WindowEvent winclose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton car1;
    private javax.swing.JButton car2;
    private javax.swing.JButton car3;
    private javax.swing.JButton car4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
