package Menu_System;

import DB_Connect.testform;
import GameState.GameStateManager;
import GameState.RaceLevelLoader;
import Maincarrace.MainF;
import gameloop.GameLoop;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

public class Menu extends JFrame {

    /** Creates new form CarManu */
    public Menu() {
        setUndecorated(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        start1 = new javax.swing.JButton();
        multiplayer1 = new javax.swing.JButton();
        highScore = new javax.swing.JButton();
        help = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        turboRacing = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        start1.setBackground(new java.awt.Color(-16776961,true));
        start1.setFont(new java.awt.Font("Monospaced", 1, 18));
        start1.setForeground(new java.awt.Color(-16711681,true));
        start1.setText("START");
        start1.setToolTipText("");
        start1.setContentAreaFilled(false);
        start1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                start1mousePressed(evt);
            }
        });
        start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start1ActionPerformed(evt);
            }
        });
        jPanel1.add(start1);
        start1.setBounds(620, 170, 160, 20);

        multiplayer1.setBackground(new java.awt.Color(-16776961,true));
        multiplayer1.setFont(new java.awt.Font("Monospaced", 1, 18));
        multiplayer1.setForeground(new java.awt.Color(-16711681,true));
        multiplayer1.setText("MULTIPLAYER");
        multiplayer1.setToolTipText("");
        multiplayer1.setContentAreaFilled(false);
        multiplayer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                multiplayer1mousePressed(evt);
            }
        });
        multiplayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplayer1ActionPerformed(evt);
            }
        });
        jPanel1.add(multiplayer1);
        multiplayer1.setBounds(620, 240, 160, 23);

        highScore.setBackground(new java.awt.Color(-16776961,true));
        highScore.setFont(new java.awt.Font("Monospaced", 1, 18));
        highScore.setForeground(new java.awt.Color(-16711681,true));
        highScore.setText("HIGH SCORES");
        highScore.setToolTipText("");
        highScore.setContentAreaFilled(false);
        highScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                highScoremousePressed(evt);
            }
        });
        highScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoreActionPerformed(evt);
            }
        });
        jPanel1.add(highScore);
        highScore.setBounds(620, 310, 160, 23);

        help.setBackground(new java.awt.Color(-16776961,true));
        help.setFont(new java.awt.Font("Monospaced", 1, 18));
        help.setForeground(new java.awt.Color(-16711681,true));
        help.setText("HELP");
        help.setToolTipText("");
        help.setContentAreaFilled(false);
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpmousePressed(evt);
            }
        });
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jPanel1.add(help);
        help.setBounds(620, 390, 160, 23);

        exit.setBackground(new java.awt.Color(-16776961,true));
        exit.setFont(new java.awt.Font("Monospaced", 1, 18));
        exit.setForeground(new java.awt.Color(-16711681,true));
        exit.setText("EXIT");
        exit.setToolTipText("");
        exit.setContentAreaFilled(false);
        exit.setPreferredSize(new java.awt.Dimension(153, 33));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu.this.mousePressed(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(620, 470, 160, 23);

        turboRacing.setFont(new java.awt.Font("Tekton Pro Cond", 3, 48)); // NOI18N
        turboRacing.setForeground(new java.awt.Color(255, 0, 51));
        turboRacing.setText("TURBO RACING");
        turboRacing.setToolTipText("");
        turboRacing.setName(""); // NOI18N
        jPanel1.add(turboRacing);
        turboRacing.setBounds(570, 40, 260, 70);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("iReport");
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 560, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_exitActionPerformed

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mousePressed

    private void highScoremousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highScoremousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_highScoremousePressed

    private void highScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoreActionPerformed
        
    }//GEN-LAST:event_highScoreActionPerformed

    private void helpmousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpmousePressed
        
    }//GEN-LAST:event_helpmousePressed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
//        close();
        Help help = new Help();
        help.setVisible(true);
    }//GEN-LAST:event_helpActionPerformed

    private void start1mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start1mousePressed
        
    }//GEN-LAST:event_start1mousePressed

    private void start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start1ActionPerformed
        close();
        CarSelect cs = new CarSelect();
        cs.setVisible(true);
    }//GEN-LAST:event_start1ActionPerformed

    private void multiplayer1mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplayer1mousePressed
        
    }//GEN-LAST:event_multiplayer1mousePressed

    private void multiplayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplayer1ActionPerformed
        close();
        GameLoop.type = "2p"; //sets mode in Game Loop to 2 player
        new MainF();//opens main car race
        //new MainF();//opens main car race
    }//GEN-LAST:event_multiplayer1ActionPerformed
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
              }
        });
    }
    
    //closes the Jframe
    private void close() {
        WindowEvent winclose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton help;
    private javax.swing.JButton highScore;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton multiplayer1;
    private javax.swing.JButton start1;
    private javax.swing.JLabel turboRacing;
    // End of variables declaration//GEN-END:variables

}
