package Menu_System;

import Maincarrace.MainF;
import System.GameWindow;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

public class Pause extends JFrame {
    GameWindow k = new GameWindow("", MainF.width, MainF.height);
    
    
    /** Creates new form CarManu */
    public Pause() {
        setUndecorated(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        help = new javax.swing.JButton();
        turboRacing = new javax.swing.JLabel();
        highScores = new javax.swing.JButton();
        resume = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        exit.setBackground(new java.awt.Color(-16776961,true));
        exit.setFont(new java.awt.Font("Monospaced", 1, 18));
        exit.setForeground(new java.awt.Color(-16711681,true));
        exit.setText("EXIT");
        exit.setToolTipText("");
        exit.setContentAreaFilled(false);
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit.setPreferredSize(new java.awt.Dimension(153, 33));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pause.this.mousePressed(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(660, 480, 160, 23);

        help.setBackground(new java.awt.Color(-16776961,true));
        help.setFont(new java.awt.Font("Monospaced", 1, 18));
        help.setForeground(new java.awt.Color(-16711681,true));
        help.setText("HELP");
        help.setToolTipText("");
        help.setContentAreaFilled(false);
        help.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpmousePressed(evt);
            }
        });
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jPanel1.add(help);
        help.setBounds(660, 390, 160, 23);

        turboRacing.setFont(new java.awt.Font("Tekton Pro Cond", 3, 48)); // NOI18N
        turboRacing.setForeground(new java.awt.Color(255, 0, 51));
        turboRacing.setText("   Game Paused");
        turboRacing.setToolTipText("");
        turboRacing.setName(""); // NOI18N
        jPanel1.add(turboRacing);
        turboRacing.setBounds(600, 40, 260, 70);

        highScores.setBackground(new java.awt.Color(-16776961,true));
        highScores.setFont(new java.awt.Font("Monospaced", 1, 18));
        highScores.setForeground(new java.awt.Color(-16711681,true));
        highScores.setText("HIGH SCORES");
        highScores.setToolTipText("");
        highScores.setContentAreaFilled(false);
        highScores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        highScores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                highScoresmousePressed(evt);
            }
        });
        highScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoresActionPerformed(evt);
            }
        });
        jPanel1.add(highScores);
        highScores.setBounds(660, 290, 160, 23);

        resume.setBackground(new java.awt.Color(-16776961,true));
        resume.setFont(new java.awt.Font("Monospaced", 1, 18));
        resume.setForeground(new java.awt.Color(-16711681,true));
        resume.setText("RESUME");
        resume.setToolTipText("");
        resume.setContentAreaFilled(false);
        resume.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resumemousePressed(evt);
            }
        });
        resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeActionPerformed(evt);
            }
        });
        jPanel1.add(resume);
        resume.setBounds(660, 200, 160, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        
        GameWindow k = new GameWindow("", MainF.width, MainF.height);
        close();
        close(k);
        /*Menu menu = new Menu();
        menu.setVisible(true);*/
        
    }//GEN-LAST:event_exitActionPerformed

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mousePressed

    private void helpmousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpmousePressed
        
    }//GEN-LAST:event_helpmousePressed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        //close();
        Help help = new Help();
        help.setVisible(true);
    }//GEN-LAST:event_helpActionPerformed

    private void highScoresmousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highScoresmousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_highScoresmousePressed

    private void highScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highScoresActionPerformed

    private void resumemousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resumemousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_resumemousePressed

    private void resumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeActionPerformed
        // TODO add your handling code here:
        close();
        //MainF k = new MainF();
    }//GEN-LAST:event_resumeActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pause().setVisible(true);
              }
        });
    }
    
    private void close() {
        WindowEvent winClose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
    }
    
    
    private void close(MainF s) {
        WindowEvent winClose = new WindowEvent(s,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
    }
    private void close(GameWindow k) {
        WindowEvent winClose = new WindowEvent(k,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClose);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton help;
    private javax.swing.JButton highScores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resume;
    private javax.swing.JLabel turboRacing;
    // End of variables declaration//GEN-END:variables

}
